# Change these first
# see https://github.com/superrr-vpn/status
owner: RealYalaSo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Yalaso Tech - Home page
    url: https://yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Home page old
    url: https://superrr-vpn.yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Home page
    url: https://turbo-max.yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Subscription
    url: https://turbo-max.yalaso.top/subscriptions.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Sign in
    url: https://turbo-max.yalaso.top/signin.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Terms
    url: https://turbo-max.yalaso.top/terms_of_service.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Policy
    url: https://turbo-max.yalaso.top/policy.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: API
    url: https://api.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: API Auth
    url: https://api.yalaso.top/api/v1/host/auth
    method: POST
    headers:
      - "Content-Type: application/json"
      - "User-Agent: GitHub Action"
    body: '{ "username": "username", "password": "password", "client_ip": "client_ip", "host_ip": "host_ip", "tx_id": "tx_id" }'
    expectedStatusCodes:
      - 200
      - 400
    maxResponseTime: 2000
  - name: Node - ae-b061422e.yalaso.top
    url: http://ae-b061422e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - au-0d374460.yalaso.top
    url: http://au-0d374460.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - au-b06145ad.yalaso.top
    url: http://au-b06145ad.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-179a516e.yalaso.top
    url: http://ca-179a516e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-23b77f40.yalaso.top
    url: http://ca-23b77f40.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-6790b1e9.yalaso.top
    url: http://ca-6790b1e9.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ch-b32bb087.yalaso.top
    url: http://ch-b32bb087.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-034855ca.yalaso.top
    url: http://de-034855ca.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-053d2b7c.yalaso.top
    url: http://de-053d2b7c.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-0d261edf.yalaso.top
    url: http://fr-0d261edf.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-b9579728.yalaso.top
    url: http://fr-b9579728.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-03087f26.yalaso.top
    url: http://gb-03087f26.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-053d3db7.yalaso.top
    url: http://gb-053d3db7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-8b1ccf30.yalaso.top
    url: http://gb-8b1ccf30.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-b9b3d80f.yalaso.top
    url: http://gb-b9b3d80f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ie-34d3f93e.yalaso.top
    url: http://ie-34d3f93e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - in-344234fc.yalaso.top
    url: http://in-344234fc.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - jp-2bcfaff7.yalaso.top
    url: http://jp-2bcfaff7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - kr-0d7c7a1d.yalaso.top
    url: http://kr-0d7c7a1d.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - nl-bc7417b6.yalaso.top
    url: http://nl-bc7417b6.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-2d59e4d7.yalaso.top
    url: http://ru-2d59e4d7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-b90442ee.yalaso.top
    url: http://ru-b90442ee.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-b9044395.yalaso.top
    url: http://ru-b9044395.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - se-0d33a168.yalaso.top
    url: http://se-0d33a168.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - sg-36a9833d.yalaso.top
    url: http://sg-36a9833d.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - sg-36a983c6.yalaso.top
    url: http://sg-36a983c6.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - sg-67539fc1.yalaso.top
    url: http://sg-67539fc1.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - tr-2d50afca.yalaso.top
    url: http://tr-2d50afca.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - tr-54360d94.yalaso.top
    url: http://tr-54360d94.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ua-8200ea14.yalaso.top
    url: http://ua-8200ea14.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-03511e7f.yalaso.top
    url: http://us-03511e7f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-12dac159.yalaso.top
    url: http://us-12dac159.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-22d02de8.yalaso.top
    url: http://us-22d02de8.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2501d0d2.yalaso.top
    url: http://us-2501d0d2.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2501d3cc.yalaso.top
    url: http://us-2501d3cc.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2656834a.yalaso.top
    url: http://us-2656834a.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-265df6ca.yalaso.top
    url: http://us-265df6ca.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2d410906.yalaso.top
    url: http://us-2d410906.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2d410907.yalaso.top
    url: http://us-2d410907.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2e159fc1.yalaso.top
    url: http://us-2e159fc1.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-5c26a98c.yalaso.top
    url: http://us-5c26a98c.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "5 * * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yalaso.top
  logoUrl: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  favicon: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  name: Status
  introTitle: "Status of Superrr VPN"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RealYalaSo/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
