# Change these first
# see https://github.com/superrr-vpn/status
owner: RealYalaSo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Yalaso Tech - Home page
    url: https://yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Home page old
    url: https://superrr-vpn.yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Home page
    url: https://turbo-max.yalaso.top
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Subscription
    url: https://turbo-max.yalaso.top/subscriptions.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Sign in
    url: https://turbo-max.yalaso.top/signin.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Terms
    url: https://turbo-max.yalaso.top/terms_of_service.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Turbo Max - Policy
    url: https://turbo-max.yalaso.top/policy.html
    method: GET
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: API
    url: https://api.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: API Auth
    url: https://api.yalaso.top/api/v1/host/auth
    method: POST
    headers:
      - "Content-Type: application/json"
      - "User-Agent: GitHub Action"
    body: '{ "username": "username", "password": "password", "client_ip": "client_ip", "host_ip": "host_ip", "tx_id": "tx_id" }'
    expectedStatusCodes:
      - 200
      - 400
    maxResponseTime: 2000
  - name: Node - sg-8ba2360b.yalaso.top
    url: http://sg-8ba2360b.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-aabb97b2.yalaso.top
    url: http://us-aabb97b2.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - au-ac69bc5e.yalaso.top
    url: http://au-ac69bc5e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-ace99aa8.yalaso.top
    url: http://us-ace99aa8.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - nl-ace93e8a.yalaso.top
    url: http://nl-ace93e8a.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-acea110f.yalaso.top
    url: http://us-acea110f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-0238b28e.yalaso.top
    url: http://ru-0238b28e.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-0238b28f.yalaso.top
    url: http://ru-0238b28f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-0238b399.yalaso.top
    url: http://gb-0238b399.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-25092317.yalaso.top
    url: http://us-25092317.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ru-2d8102a9.yalaso.top
    url: http://ru-2d8102a9.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2d9641b8.yalaso.top
    url: http://us-2d9641b8.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-2d538c95.yalaso.top
    url: http://us-2d538c95.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - jp-2d596d23.yalaso.top
    url: http://jp-2d596d23.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - jp-2d596d24.yalaso.top
    url: http://jp-2d596d24.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-2d596f1f.yalaso.top
    url: http://gb-2d596f1f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-05082110.yalaso.top
    url: http://gb-05082110.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - gb-05082132.yalaso.top
    url: http://gb-05082132.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-480eb83f.yalaso.top
    url: http://us-480eb83f.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-55d06cf7.yalaso.top
    url: http://ca-55d06cf7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - ca-55d06cfe.yalaso.top
    url: http://ca-55d06cfe.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-555ad8aa.yalaso.top
    url: http://fr-555ad8aa.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-592cc6ef.yalaso.top
    url: http://de-592cc6ef.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - us-5cdf1ea7.yalaso.top
    url: http://us-5cdf1ea7.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-5ee8f743.yalaso.top
    url: http://fr-5ee8f743.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - fr-5ee8f748.yalaso.top
    url: http://fr-5ee8f748.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-5fa44465.yalaso.top
    url: http://de-5fa44465.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000
  - name: Node - de-5fa4447d.yalaso.top
    url: http://de-5fa4447d.yalaso.top/api/v1/ping
    method: POST
    headers:
      - "User-Agent: GitHub Action"
    maxResponseTime: 2000

workflowSchedule:
  graphs: "5 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 1 * * *"
  summary: "5 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "5 * * * *"
  uptime: "*/10 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.yalaso.top
  logoUrl: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  favicon: https://raw.githubusercontent.com/RealYalaSo/status/master/assets/icon.png
  name: Status
  introTitle: "Status of Superrr VPN"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/RealYalaSo/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
